### ISSUE TITLE
Code snippet for adding findings/evidence to cucumber multipart import?

### ISSUE THREAD

**Issue by robertlagrant** [Xray-App/xray-code-snippets#4]
I'd love an example showing how to add evidence alongside the [raw results import](https://docs.getxray.app/display/XRAYCLOUD/Import+Execution+Results+-+REST+v2#ImportExecutionResultsRESTv2-CucumberJSONresultsMultipart). Our particular case is we generate a .webm video from Playwright as we step through our BDD tests, and it would be great to automatically attach the video as evidence alongside the BDD results upload.

**Comment by bitcoder** [comment]
References:

- https://confluence.atlassian.com/jirakb/how-to-add-an-attachment-to-a-jira-issue-using-rest-api-699957734.html
- https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-attachments/#api-rest-api-3-issue-issueidorkey-attachments-post

**Comment by bitcoder** [comment]
Added examples on how to upload attachment(s) to an issue (e.g, Test, Test Execution, Test Plan) in:

- Python: https://github.com/Xray-App/xray-code-snippets/blob/main/use_cases/jira_rest_api_usage/python/add_attachments_to_issue.py 
- JavaScript: https://github.com/Xray-App/xray-code-snippets/blob/main/use_cases/jira_rest_api_usage/js/add_attachments_to_issue.js

In sum, you have to upload the test results.. obtain the Test Execution issue key from the response and then do another request, this time to Jira's REST API, to upload attachments.

**Comment by robertlagrant** [comment]
Thank you for all those details. Much appreciated.

**Comment by bitcoder** [comment]
@robertlagrant , 
to clarify, we can have attachments at different leves:

- in the Test Run, globally, as evidence
- in the Test Run, at each step/Gherkin statement level
- in the Test Execution issue itself (this is less common)

In Xray server/datacenter, evidence on the Test Runs is stored as attachments in the underlying Test Execution issue
In Xray cloud, evidence on the Test Runs is stored in Xray's cloud infrastructure itself; there's a storage limit (reach out Xray support team for more info on that)

If you decide to add attachments directly to the Test Execution issue (as shown on the snippets above), then it uses Jira way of managing attachments (i.e., a local directory on Jira server or the cloud infrastructure of Atlassian in the case of Jira cloud).

Hope it clarifies!
