### ISSUE TITLE
How to create test steps in Xray using REST API or GraphQL

### ISSUE THREAD

**Issue by RithikTM** [Xray-App/xray-code-snippets#6]
I am trying to create a test step in Xray JIRA using REST API. Could someone give me a correct procedure to do this from authorization to correct end point (What api token we must use, what server instance to use, what result must we expect) in post man or Jmeter. I have already looked into the Xray documentation but further more clarity will be greatly appreciated

**Comment by bitcoder** [comment]
@RithikTM  are you using Xray on Jira Cloud or Xray on Jira datacenter (on-premises), as there are nuances on the related APIs?

**Comment by bitcoder** [comment]
closed for lack of feedback
